

This is a [SKY](https://chabefer.github.io/SKY/index.html) website examining the performances of methods correcting for publication bias.

This website contains:

* [Description of the methods](Methods.html)
* [Results from simulations](Simulations.html)
* [Results on real data](Estimation_Pub_bias.html)

The main results of the project so far can be summarized in the performance of the various estimators of the true effect compared to pre-registered replications.
The analysis behind this data is available [here](Estimation_Pub_Bias.html).
The following graph shows it all:

```{r PerfMethods,echo=FALSE,results=FALSE,fig.cap='Performance of various estimators of an effect compared to pre-registered replications',fig.align='center',fig.width=10}
# downloading the data
# connecting
source(here::here("idsql.R"))
SKY <- dbConnect(MySQL(), dbname="SKY",
                     user=myid, password=mypass, host=myhost)
# sending
PerfMethodsPubBias <- dbReadTable(SKY,"Correct_Pub_Bias") %>%
                        pivot_longer(
                          cols=2:4,
                          names_to="Criteria",
                          values_to="Bias" )  %>%
                        mutate(
                          Criteria=factor(Criteria,levels=c("MeanBias","MAD","RMSE")),
                          Method = if_else(Method=="Meta","Meta-analysis",Method),
                          Method=factor(Method,levels=c("Original","Meta-analysis","PEESE","PEESEpos","FATPETPEESEpos","ppCurve","SelModel"))
                        )
# disconnecting
dbDisconnect(SKY)

# plotting 
ggplot(PerfMethodsPubBias,aes(x=Criteria,y=Bias,fill=Method))+
  geom_bar(stat='identity', position=position_dodge())+
  theme_bw()
```

The original estimates have large baises.
Meta-analysis divides the mean bias by two.
The PEESE and PEESEpos methods brings the bias further down by 40\%.
The other criteria tell a similar story.
This data makes the PEESE and PEESEpos estimators the best estimators so far to estimate true treatment effects using the published record.

If you have comments on this project, please post them on the corresponding [GitHub comment page](https://github.com/chabefer/SKY_Correct_Pub_Bias/discussions).

If you want to alter this project, please do so on its [GitHub repo](https://github.com/chabefer/SKY_Correct_Pub_Bias).

